/* Automatically generated by wasm2c */
#ifndef OBJECT_CONVERTED_H_GENERATED_
#define OBJECT_CONVERTED_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;
extern wasm_rt_memory_t* w2c_env_0x5F_linear_memory(struct w2c_env*);
extern u32* w2c_env_0x5F_stack_pointer(struct w2c_env*);

typedef struct w2c_foo__object {
  /* import: 'env' '__linear_memory' */
  wasm_rt_memory_t *w2c_env_0x5F_linear_memory;
  /* import: 'env' '__stack_pointer' */
  u32 *w2c_env_0x5F_stack_pointer;
} w2c_foo__object;

void wasm2c_foo__object_instantiate(w2c_foo__object*, struct w2c_env*);
void wasm2c_foo__object_free(w2c_foo__object*);
wasm_rt_func_type_t wasm2c_foo__object_get_func_type(uint32_t param_count, uint32_t result_count, ...);

extern const u64 wasm2c_foo__object_min_env_0x5F_linear_memory;
extern const u64 wasm2c_foo__object_max_env_0x5F_linear_memory;
extern const u8 wasm2c_foo__object_is64_env_0x5F_linear_memory;
extern const u32 wasm2c_foo__object_pagesize_env_0x5F_linear_memory;

#ifdef __cplusplus
}
#endif

#endif  /* OBJECT_CONVERTED_H_GENERATED_ */
