/* Automatically generated by wasm2c */
#ifndef TWEETNACL_WASM_H_GENERATED_
#define TWEETNACL_WASM_H_GENERATED_

#include "wasm-rt.h"

#include <stdint.h>

#ifndef WASM_RT_CORE_TYPES_DEFINED
#define WASM_RT_CORE_TYPES_DEFINED
typedef uint8_t u8;
typedef int8_t s8;
typedef uint16_t u16;
typedef int16_t s16;
typedef uint32_t u32;
typedef int32_t s32;
typedef uint64_t u64;
typedef int64_t s64;
typedef float f32;
typedef double f64;
#endif

#ifdef __cplusplus
extern "C" {
#endif

struct w2c_env;

typedef struct w2c_tweetnacl {
  struct w2c_env* w2c_env_instance;
  u32 w2c_g0;
  u32 w2c_0x5F_dso_handle;
  u32 w2c_0x5F_data_end;
  u32 w2c_0x5F_stack_low;
  u32 w2c_0x5F_stack_high;
  u32 w2c_0x5F_global_base;
  u32 w2c_0x5F_heap_base;
  u32 w2c_0x5F_heap_end;
  u32 w2c_0x5F_memory_base;
  u32 w2c_0x5F_table_base;
  u32 w2c_0x5F_wasm_first_page_end;
  wasm_rt_memory_t w2c_memory;
} w2c_tweetnacl;

void wasm2c_tweetnacl_instantiate(w2c_tweetnacl*, struct w2c_env*);
void wasm2c_tweetnacl_free(w2c_tweetnacl*);
wasm_rt_func_type_t wasm2c_tweetnacl_get_func_type(uint32_t param_count, uint32_t result_count, ...);

/* import: 'env' 'randombytes' */
void w2c_env_randombytes(struct w2c_env*, u32, u64);

/* export: 'memory' */
wasm_rt_memory_t* w2c_tweetnacl_memory(w2c_tweetnacl* instance);

/* export: '__wasm_call_ctors' */
void w2c_tweetnacl_0x5F_wasm_call_ctors(w2c_tweetnacl*);

/* export: 'crypto_verify_16_tweet' */
u32 w2c_tweetnacl_crypto_verify_16_tweet(w2c_tweetnacl*, u32, u32);

/* export: 'crypto_verify_32_tweet' */
u32 w2c_tweetnacl_crypto_verify_32_tweet(w2c_tweetnacl*, u32, u32);

/* export: 'crypto_core_salsa20_tweet' */
u32 w2c_tweetnacl_crypto_core_salsa20_tweet(w2c_tweetnacl*, u32, u32, u32, u32);

/* export: 'crypto_core_hsalsa20_tweet' */
u32 w2c_tweetnacl_crypto_core_hsalsa20_tweet(w2c_tweetnacl*, u32, u32, u32, u32);

/* export: 'crypto_stream_salsa20_tweet_xor' */
u32 w2c_tweetnacl_crypto_stream_salsa20_tweet_xor(w2c_tweetnacl*, u32, u32, u64, u32, u32);

/* export: 'crypto_stream_salsa20_tweet' */
u32 w2c_tweetnacl_crypto_stream_salsa20_tweet(w2c_tweetnacl*, u32, u64, u32, u32);

/* export: 'crypto_stream_xsalsa20_tweet' */
u32 w2c_tweetnacl_crypto_stream_xsalsa20_tweet(w2c_tweetnacl*, u32, u64, u32, u32);

/* export: 'crypto_stream_xsalsa20_tweet_xor' */
u32 w2c_tweetnacl_crypto_stream_xsalsa20_tweet_xor(w2c_tweetnacl*, u32, u32, u64, u32, u32);

/* export: 'crypto_onetimeauth_poly1305_tweet' */
u32 w2c_tweetnacl_crypto_onetimeauth_poly1305_tweet(w2c_tweetnacl*, u32, u32, u64, u32);

/* export: 'crypto_onetimeauth_poly1305_tweet_verify' */
u32 w2c_tweetnacl_crypto_onetimeauth_poly1305_tweet_verify(w2c_tweetnacl*, u32, u32, u64, u32);

/* export: 'crypto_secretbox_xsalsa20poly1305_tweet' */
u32 w2c_tweetnacl_crypto_secretbox_xsalsa20poly1305_tweet(w2c_tweetnacl*, u32, u32, u64, u32, u32);

/* export: 'crypto_secretbox_xsalsa20poly1305_tweet_open' */
u32 w2c_tweetnacl_crypto_secretbox_xsalsa20poly1305_tweet_open(w2c_tweetnacl*, u32, u32, u64, u32, u32);

/* export: 'crypto_scalarmult_curve25519_tweet' */
u32 w2c_tweetnacl_crypto_scalarmult_curve25519_tweet(w2c_tweetnacl*, u32, u32, u32);

/* export: 'crypto_scalarmult_curve25519_tweet_base' */
u32 w2c_tweetnacl_crypto_scalarmult_curve25519_tweet_base(w2c_tweetnacl*, u32, u32);

/* export: 'crypto_box_curve25519xsalsa20poly1305_tweet_keypair' */
u32 w2c_tweetnacl_crypto_box_curve25519xsalsa20poly1305_tweet_keypair(w2c_tweetnacl*, u32, u32);

/* export: 'crypto_box_curve25519xsalsa20poly1305_tweet_beforenm' */
u32 w2c_tweetnacl_crypto_box_curve25519xsalsa20poly1305_tweet_beforenm(w2c_tweetnacl*, u32, u32, u32);

/* export: 'crypto_box_curve25519xsalsa20poly1305_tweet_afternm' */
u32 w2c_tweetnacl_crypto_box_curve25519xsalsa20poly1305_tweet_afternm(w2c_tweetnacl*, u32, u32, u64, u32, u32);

/* export: 'crypto_box_curve25519xsalsa20poly1305_tweet_open_afternm' */
u32 w2c_tweetnacl_crypto_box_curve25519xsalsa20poly1305_tweet_open_afternm(w2c_tweetnacl*, u32, u32, u64, u32, u32);

/* export: 'crypto_box_curve25519xsalsa20poly1305_tweet' */
u32 w2c_tweetnacl_crypto_box_curve25519xsalsa20poly1305_tweet(w2c_tweetnacl*, u32, u32, u64, u32, u32, u32);

/* export: 'crypto_box_curve25519xsalsa20poly1305_tweet_open' */
u32 w2c_tweetnacl_crypto_box_curve25519xsalsa20poly1305_tweet_open(w2c_tweetnacl*, u32, u32, u64, u32, u32, u32);

/* export: 'crypto_hashblocks_sha512_tweet' */
u32 w2c_tweetnacl_crypto_hashblocks_sha512_tweet(w2c_tweetnacl*, u32, u32, u64);

/* export: 'crypto_hash_sha512_tweet' */
u32 w2c_tweetnacl_crypto_hash_sha512_tweet(w2c_tweetnacl*, u32, u32, u64);

/* export: 'crypto_sign_ed25519_tweet_keypair' */
u32 w2c_tweetnacl_crypto_sign_ed25519_tweet_keypair(w2c_tweetnacl*, u32, u32);

/* export: 'crypto_sign_ed25519_tweet' */
u32 w2c_tweetnacl_crypto_sign_ed25519_tweet(w2c_tweetnacl*, u32, u32, u32, u64, u32);

/* export: 'crypto_sign_ed25519_tweet_open' */
u32 w2c_tweetnacl_crypto_sign_ed25519_tweet_open(w2c_tweetnacl*, u32, u32, u32, u64, u32);

/* export: '__dso_handle' */
u32* w2c_tweetnacl_0x5F_dso_handle(w2c_tweetnacl* instance);

/* export: '__data_end' */
u32* w2c_tweetnacl_0x5F_data_end(w2c_tweetnacl* instance);

/* export: '__stack_low' */
u32* w2c_tweetnacl_0x5F_stack_low(w2c_tweetnacl* instance);

/* export: '__stack_high' */
u32* w2c_tweetnacl_0x5F_stack_high(w2c_tweetnacl* instance);

/* export: '__global_base' */
u32* w2c_tweetnacl_0x5F_global_base(w2c_tweetnacl* instance);

/* export: '__heap_base' */
u32* w2c_tweetnacl_0x5F_heap_base(w2c_tweetnacl* instance);

/* export: '__heap_end' */
u32* w2c_tweetnacl_0x5F_heap_end(w2c_tweetnacl* instance);

/* export: '__memory_base' */
u32* w2c_tweetnacl_0x5F_memory_base(w2c_tweetnacl* instance);

/* export: '__table_base' */
u32* w2c_tweetnacl_0x5F_table_base(w2c_tweetnacl* instance);

/* export: '__wasm_first_page_end' */
u32* w2c_tweetnacl_0x5F_wasm_first_page_end(w2c_tweetnacl* instance);

#ifdef __cplusplus
}
#endif

#endif  /* TWEETNACL_WASM_H_GENERATED_ */
